id: P000295
initial_creation_type: ocr
created_at: 10/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30434
  title: དགེ་བའི་བཤེས་གཉེན་ཆེན་པོ་ཤེས་རབ་རྒྱ་མཚོ།
  author: ''
  volumes:
    40a009302b6d4ca4b84748359220e002:
      image_group_id: I1KG14929
      title: Volume 1 of dge ba'i bshes gnyen chen po shes rab rgya mtsho
      volume_number: 1
      total_pages: 544
      base_file: v001.txt
